### ISSUE TITLE
What is the default login and password ?

### ISSUE THREAD

**Issue by mdenavac** [zimbatm/camlistore-docker#1]
Might be useful to connect to the ui :)

**Comment by zimbatm** [comment]
Might be :) Especially since the default config disallows access from everything except the container's localhost. The best way is to push a custom config on a web server and then run the container with the `-configfile http://url.to/config.json` appended at the end.

**Comment by zimbatm** [comment]
Sample of the generated config file:

``` json
{
    "auth": "localhost",
    "listen": ":3179",
    "identity": "43C7D1C3",
    "identitySecretRing": "/data/.config/camlistore/identity-secring.gpg",
    "blobPath": "/data/var/camlistore/blobs",
    "kvIndexFile": "/data/var/camlistore/camli-index.kvdb"
}
```

**Comment by zimbatm** [comment]
I don't know what's the best way to manage config in docker. Some seem to use etcd or consul, ...

**Comment by mdenavac** [comment]
I don't know either... Thank you !
